const {
  jsonToMarkdownTable,
  renderVoteIcon,
  renderHeaderCell,
  generateMarkdownHeader,
  generateMarkdownRows,
} = require('../.github/scripts/vote_tracker/markdownTable.js');

describe('renderVoteIcon', () => {
  it('returns correct emoji for known values', () => {
    expect(renderVoteIcon("In favor")).toContain("👍");
    expect(renderVoteIcon("Against")).toContain("👎");
    expect(renderVoteIcon("Abstain")).toContain("👀");
    expect(renderVoteIcon("Not participated")).toContain("🔕");
  });

  it('returns raw value if not in icon map', () => {
    expect(renderVoteIcon("Unknown")).toContain("Unknown");
  });
});

describe('renderHeaderCell', () => {
  const titles = {
    name: "GitHub user name",
    votes: "Total votes",
  };

  it('returns GitHub issue link if key includes $$', () => {
    const result = renderHeaderCell("Voting$$123", titles, "org", "repo");
    expect(result).toContain("https://github.com/org/repo/issues/123");
    expect(result).toContain("[Voting]");
  });

  it('returns the human-readable title for normal keys when present in the titles map', () => {
    const result = renderHeaderCell("name", titles, "org", "repo");
    expect(result).toBe("GitHub user name");
    expect(result).not.toContain("<span");
  });

  it('returns the raw key when no title mapping exists', () => {
    const result = renderHeaderCell("unknownField", titles, "org", "repo");
    expect(result).toBe("unknownField");
  });
});

describe('generateMarkdownHeader', () => {
  it('returns proper markdown header with tooltips or links', () => {
    const keys = ["name", "Voting$$123"];
    const titles = { name: "GitHub username" };
    const result = generateMarkdownHeader(keys, titles, "org", "repo");

    expect(result).toContain("| [Voting]");
    expect(result).toContain("[Voting](https://github.com/org/repo/issues/123)");
    expect(result).toContain("---");
  });
});

describe('generateMarkdownRows', () => {
  const keys = ["name", "vote$$456"];
  const data = [
    { name: "octocat", "vote$$456": "In favor" },
    { name: "monalisa", "vote$$456": "Abstain" },
  ];

  it('renders GitHub links and vote icons', () => {
    const result = generateMarkdownRows(data, keys);
    expect(result).toContain("[octocat](https://github.com/octocat)");
    expect(result).toContain("👀"); // Abstain icon
    expect(result).toContain("👍"); // In favor icon
  });
});

describe('jsonToMarkdownTable', () => {
  const data = [
    {
      name: "octocat",
      lastParticipatedVoteTime: "2024-12-01",
      isVotedInLast3Months: true,
      agreeCount: 3,
      disagreeCount: 0,
      abstainCount: 1,
      notParticipatingCount: 0,
    },
  ];

  // Sample data for visualization test
  const visualizationData = [
    {
      name: "user1",
      "Proposal$$123": "In favor",
      lastParticipatedVoteTime: "2025-06-01",
      isVotedInLast3Months: true,
      agreeCount: 5,
      disagreeCount: 2,
    },
    {
      name: "user2",
      "Proposal$$123": "Against",
      lastParticipatedVoteTime: "2025-05-15",
      isVotedInLast3Months: false,
      abstainCount: 1,
      notParticipatingCount: 3,
    },
    {
      name: "user3",
      "Proposal$$123": "Abstain",
      lastVoteClosedTime: "2025-06-20",
      // Missing some fields to test normalization
    },
  ];

  it('generates full markdown table string', async () => {
    const result = await jsonToMarkdownTable(data, "org", "repo");
    expect(result).toContain(`---\ntitle: TSC Voting Overview`);
    expect(result).toContain("[octocat](https://github.com/octocat)");
    expect(result).toContain("In favor");
  });

  it('returns empty string for empty input', async () => {
    const result = await jsonToMarkdownTable([], "org", "repo");
    expect(result).toBe("");
  });

  it('should visualize input JSON and verify Markdown table', async () => {

    // Generate Markdown table
    const result = await jsonToMarkdownTable(visualizationData, "org", "repo");

    // Assertions to verify correctness
    expect(result).toContain('[user1](https://github.com/user1)'); // GitHub link for name
    expect(result).toContain('👍'); // In favor emoji
    expect(result).toContain('👎'); // Against emoji
    expect(result).toContain('👀'); // Abstain emoji
    expect(result).toContain('[Proposal](https://github.com/org/repo/issues/123)'); // Issue link
    expect(result).toContain('N/A'); // Normalized missing fields
    expect(result).toContain('---'); // Markdown separator
    expect(result).toContain('<!-- This file is generated by a script'); // Header comment
  });
});
