profiles:
  default:
    duration: 4w
    pass_threshold: 51
    periodic_status_check: "1 week"
    close_on_passing: true
    close_on_passing_min_wait: "7 days"
    allowed_voters:
      teams:
        - tsc_members