env:
  es6: true
  node: true
  commonjs: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - "!.*"
  - "**/node_modules/.*"
  - "**/dist/.*"
  - "**/coverage/.*"
  - "*.json"

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  requireConfigFile: false

extends:
  - eslint:recommended
  - plugin:github/recommended

rules:
  {
    "camelcase": "off",
    "eslint-comments/no-use": "off",
    "eslint-comments/no-unused-disable": "off",
    "i18n-text/no-en": "off",
    "import/no-commonjs": "off",
    "import/no-namespace": "off",
    "no-console": "off",
    "no-unused-vars": "off",
    "prettier/prettier": "error",
    "semi": "off",
  }
