#This action update the list of Ambassadors in the website repository. List of all Ambassadors is later rendered in the asyncapi.com website.
name: Update list of Ambassadors in the website repo

on:
  push:
    branches:
      - 'master'
    paths:
      - 'AMBASSADORS_MEMBERS.yaml'

jobs:
  update-website:
    name: Make PR on website repository with updated ambassadors list
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v4
        with:
          path: community
      - name: Checkout Another repository
        uses: actions/checkout@v4
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
      - name: Config git
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
      - name: Create branch
        working-directory: ./website
        run: |
          git checkout -b update-ambassadors-${{ github.sha }}
      - name: Convert YAML to JSON using Python
        working-directory: ./community
        run: |
          pip install pyyaml==6.0.1
          python -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)' < AMBASSADORS_MEMBERS.yaml > AMBASSADORS_MEMBERS.json
      - name: Copy ambassadors file from Current Repo to Another
        working-directory: ./website
        run: |
          cp ../community/AMBASSADORS_MEMBERS.json ./config/AMBASSADORS_MEMBERS.json
      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(community): update latest ambassadors list"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/website
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "docs(community): update latest tsc members list" --body "Updated Ambassadors list is available and this PR introduces changes with latest information about Ambassadors list" --head "update-ambassadors-${{ github.sha }}"
